Dev environment setup (#20)
* Circle, Travis and CodeCov badges
* Coverage
* Improved codecov command in Makefile
* Makefile update. Code coverage fix
* Makefile pytest xml report with python version
* Travis update
* Travis matrix update
* Travis rework
* Travis skip cleanup
* Travis jobs
* Travis releases
* Exclude matrix
* Repository setup.
    - Linting, documentation, testing and whatnot.
* Build scripts fix + Travis package install
* Empty warning filter (None instead of re) fix for Python 3.7
* Python 3.7 warning filter compatibility fix
* Compatibility with Python 3.7 warnings module
* Fix: re.Pattern is only available in Python > 3.6
* Do not enforce binary scipy
* Types, imports and backslashes fix
* Documentation modules and formatting
* Fix Pylint misbehaviour when fatf was installed as editable
* pylint error fix (version update)
    - internal error with sending report for module ['fatf/__init__.py']
    - 'Import' object has no attribute 'infer_name_module'
* Split line before a logical operator
* v continuation
* dev branch linting
* Simplified if-else statements
* Handle TypeError raised by numpy < 1.14.x